### DISCUSSION TITLE
Unable to get drop-down working

### DISCUSSION THREAD

**Discussion by MrGde** [Nerwyn/custom-card-features#71] [Q&A]
I am trying to add a scene Drop-Down to my light entity. I created a template select with all the scenes. This part works nicely. But when I try to have a feature row with this dropdown, it's always empty. What am I doing wrong?

```yaml
type: tile
entity: light.davidaz
features:
  - type: custom:service-call
    entries:
      - type: dropdown
        entity_id: select.szene_david_az
        autofill_entity_id: true
```
