### DISCUSSION TITLE
Switch visibility of a button depending on logged in user

### DISCUSSION THREAD

**Discussion by papnak** [Nerwyn/custom-card-features#72] [Q&A] [answered]
Need help. I would like to change visibility of a button depending on the logged in user. I assume that it could be possible with a CSS, but my knowledge isn’t enough to understand how it works. Can anybody give advice?

**Comment by Nerwyn** [comment, marked as answer]
You can use a mix of CSS and templates to do this. Try adding this to your button styles.

```css
{% if hass.user.name != 'John Doe' %}
:host {
  display: none;
}
{% endif %}
```

Modify the if statement as necessary to hide or show the feature to specific users.
