### DISCUSSION TITLE
message: "extra keys not allowed @ data['entity_id']"

### DISCUSSION THREAD

**Discussion by AlexK98** [Nerwyn/custom-card-features#75] [General]
Hello,
trying to create a slider control to set Float Voltage setting of the hybrid inverter via mqtt.
And I get the following error:

![image](https://github.com/user-attachments/assets/0396b31e-714d-4b78-849f-a6ac195ea59e)

In browser console it looks like this:
```
code: "invalid_format"
​message: "extra keys not allowed @ data['entity_id']"
``` 
![image](https://github.com/user-attachments/assets/28f963fa-8f37-4ff5-9b98-82bdff28dca7)

here is the code of my helper:
```
input_number:
  float_voltage_slider:
    name: "Float Voltage Slider"
    min: 52.0
    max: 58.0
    step: 0.1
    mode: slider
``` 

here is the code of my card:
```
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: input_number.float_voltage_slider
        range:
          - 52
          - 58
        tap_action:
          action: perform-action
          perform_action: mqtt.publish
          target:
            entity_id: input_number.float_voltage_slider
          data:
            topic: PowMr/DeviceControl/Set_Command
            payload: PBFT{{states('input_number.float_voltage_slider')}}
        step: 0.1
        haptics: false
        thumb: line
        label: "{{ value | float }}"
        autofill_entity_id: true
type: tile
entity: sensor.powmr_inverter_battery_float_voltage
name: Float
``` 

I'm not sure what should be in the:
```
tap_action:
  target:
    entity_id: ??????????????????????
``` 

Also, these MQTT related fields, so some reason, where not automatically enabled:

![image](https://github.com/user-attachments/assets/9513fac7-99d6-4086-82f3-444a638d9fa7)

Thanks for the help.

**Comment by Nerwyn** [comment]
Try disabling autofill and removing the target.

**Reply by AlexK98** [reply]
@Nerwyn 
I disabled autofill, removed target and now there is no error message. But whenever i change value of slider it gets back to initial value and mqtt command is not sent as sensor's value is not changing. :(
what else could cause the problem?

**Reply by Nerwyn** [reply]
Make sure that the entity ID of the feature (not target) is filled in as that's there the slider value comes from. Also your action data payload is using the incorrect value. You need to use `{{ value }}` like you are for the label, not the state of the entity. If you use `states` you'll send the Home Assistant hass object value of the entity, not the value of the slider which you want to change it to.

**Reply by AlexK98** [reply]
@Nerwyn
Continue experimenting with autofill disabled and target removed.

For some reason, the {{ value | float }} in payload is not working. If I hardcode value in payload, then after moving slider's handle the mqtt request executes just fine.

**Reply by AlexK98** [reply]
well, strange. clicked "edit" for feature element once again, did not alter anything, clicked save and how mqtt with {{value | float}} in payload executes fine, but there is still the issue that handle kicks back to previous value.

**Reply by AlexK98** [reply]
@Nerwyn 
I also tried putting into the LABEL (and PAYLOAD too) expressions other than {{value | TYPE}} and they fail.
I need number formatting to be able to form proper mqtt command. Seems like this expression evaluation problem exists for both label and payload fields.

Expression like this in Label for feature element:
```
{{ "%.1f" | format(value | float) }}
``` 

results in this - slider disappears:
![image](https://github.com/user-attachments/assets/dd2f9f43-30e3-44f4-bbc4-fcd0570bc4e7)

And in console - "filter not found":
![image](https://github.com/user-attachments/assets/ad8f137e-9058-47fe-8b3b-3420602a8c6f)

What do you think?

**Reply by AlexK98** [reply]
Ok, I managed to format data properly with this code:
```
{% set identifier = "PBFT" %}
{% set number = value %}
{{ identifier ~ (number | float | round(1) if number | float % 1 != 0 else (number | int) ~ ".0") }}
``` 

But I still get issue that handle sticks to the old value despite changes applied.

I created another tile card with the my input_number helper:
![image](https://github.com/user-attachments/assets/725dd37c-70e8-454d-930c-2e016a06e24c)

Altering this blueish slider adjusts your slider component's handle position and displayed value but not vice versa:
![image](https://github.com/user-attachments/assets/6c33c5f7-a999-428f-a465-7bfeec1227b9)

Despite the changes of the value on the feature slider component, no mqtt command gets sent, which is a proper behavior, i believe.

**Reply by Nerwyn** [reply]
To clarify, the slider is now properly sending the MQTT publish action right?

It looks like you're using a helper `input_number` entity. Your slider action doesn't update this entity's value, but calls the `mqtt.publish` action instead. I'm guessing this number is the value of the entity `sensor.powmr_inverter_battery_float_voltage`? It sounds like you need to create an automation which updates the value of `input_number.float_voltage_slider` when `sensor.powmr_inverter_battery_float_voltage` changes.

The automation should look like this:

```yaml
description: ""
mode: single
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.powmr_inverter_battery_float_voltage
conditions: []
actions:
  - action: input_number.set_value
    metadata: {}
    data:
      value: '{{ states("sensor.powmr_inverter_battery_float_voltage" }}'
    target:
      entity_id: input_number.float_voltage_slider
```
