### DISCUSSION TITLE
How to get the slider value to convert it to percent in a set_speed fan call?

### DISCUSSION THREAD

**Discussion by distante** [Nerwyn/custom-card-features#83] [Q&A] [answered]
Hello, I have a question I hope you can help me.

I have a fan that has 11 speeds, but I just want to control 6 of them.

So I have created an slider feature but I can not figure out how to correctly get the value of the slider so i can set the percentage.

I have tried with `percentage: {{ value | float }}`  and `percentage: "{{ value | float }}"` but I does not work.

```yml
type: slider
entity_id: fan.esp_ventilation_controller_fan_1
range:
  - 9.09
  - 54.55
tap_action:
  action: perform-action
  target:
    entity_id:
      - fan.esp_ventilation_controller_fan_1
  confirmation: false
  perform_action: fan.set_percentage
  data:
    percentage: {{ value | float}}

    
step: 9.090909090909092
unit_of_measurement: U
label: >-
  {% set percentage = state_attr('fan.esp_ventilation_controller_fan_1',
  'percentage') | float(0) %} {% if percentage == 0 %} Off {% elif percentage <=
  (6 / 11 * 100) %} {{ ((percentage / 100) * 10) | round(0, 'floor') + 1 }} {%
  else %} Special {% endif %}
value_attribute: percentage

```
Using ``percentage: "{{ value | float }}"` sends an string which is rejected by Home assistant,.

Using ``percentage: {{ value | float }}` sends `[object object]: null` .

I got it from

> Sliders can track either the state or attribute of an entity, meaning that when that entity's state or attribute changes so will the slider to match. By default it will track the state of an entity. To change this, set Attribute to the name of the attribute you want the slider to track. In order to pass the the slider's value to an action, set the value in the action data to {{ value | float }}.

Maybe I am not understanding that correctly.

Thanks!
