### DISCUSSION TITLE
Can you align the features next to the entity name?

### DISCUSSION THREAD

**Discussion by snakeeyes5** [Nerwyn/custom-card-features#86] [Q&A]
I currently have some heavy card_mod mushroom cards that I'd like to convert to your tiles (excellent work by the way!). 

This is my current mushroom cards:
![image](https://github.com/user-attachments/assets/23a686d3-6eab-4fcd-bca9-baf07d187940)

Example using your tiles:
![image](https://github.com/user-attachments/assets/91a9428a-6284-4de0-b7f0-3f0dffcec471)

I'd like to keep the selector on the same row, like the Mushroom cards to get rid of dead space. I assume it would require card_mod, but wanted to check before getting too far along to mess around with it.

**Comment by Nerwyn** [comment]
It would require card-mod, but just to get rid of the padding around the feature that's no longer below the tile content. Most of the styling can be done with the built in style options. I was playing around this this idea a month or two ago and here's what I came up with:

```yaml
type: tile
entity: light.sunroom_ceiling
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: light.sunroom_ceiling
        range:
          - 0
          - 100
        tap_action:
          action: perform-action
          target:
            entity_id:
              - light.sunroom_ceiling
          perform_action: light.turn_on
          data:
            brightness_pct: "{{ value }}"
        step: 1
        value_attribute: brightness
        styles: ""
    styles: |-
      :host {
        height: 0px;
        position: relative;
        display: block;
        top: -49px;
        left: calc(50% - 12px);
        width: 50%;
      }
grid_options:
  columns: 12
  rows: na
card_mod:
  style: |
    hui-card-features {
      --feature-padding: 0px;
    }
```
