### DISCUSSION TITLE
Truncate text within a button

### DISCUSSION THREAD

**Discussion by AlexKusnezov** [Nerwyn/custom-card-features#87] [Q&A]
Hey, I've built a card for my power strip, which looks like this:
![Screenshot_20250221-094004](https://github.com/user-attachments/assets/b92f741d-59b4-43dd-96f0-a595909a9294)
However I have one device where it doesn't look very well:
![2025-02-21-09-24-48-427](https://github.com/user-attachments/assets/764208d7-5c35-4b26-a677-ef9ab7a1535c)

Therefore I'd rather have the text to be truncated like "Lautsp..." instead of dosplaying the whole word.

Any idea on how to achieve that?

**Comment by Nerwyn** [comment]
Add this to your feature styles. It should prevent the label from extending outside of the feature and add the overflow ellipsis.

```css
.label {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Reply by AlexKusnezov** [reply]
> Add this to your feature styles. It should prevent the label from extending outside of the feature and add the overflow ellipsis.
> 
> ```css
> .label {
>   display: block;
>   overflow: hidden;
>   text-overflow: ellipsis;
> }
> ```

thanks for getting back so quick, but unfortunately it doesn't work for me.
this makes it alligns left when its enough space:
![Screenshot_20250222-102542](https://github.com/user-attachments/assets/725285b6-48f0-4f7c-9ba4-0b0dd8596119)
and still gets into the rounded corner on small devices:
![2025-02-22-10-25-54-063](https://github.com/user-attachments/assets/83849565-7bd8-4ed1-b0cf-6c9675ec00f5)

**Reply by Nerwyn** [reply]
These additional styles should help.

```css
.label {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  text-align: center;
  margin: 0 8px;
  width: -webkit-fill-available;
  width: -moz-available;
}
```
