### DISCUSSION TITLE
Is it possible to perform multiple actions on sliders?

### DISCUSSION THREAD

**Discussion by distante** [Nerwyn/custom-card-features#90] [Q&A] [answered]
I am trying to control the volume of an android device with an slider. It works in the way that it sends the command, but the refresh takes some seconds.

```yml
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: sensor.oneplus_a3003_volume_level_music
        range:
          - 0
          - 25
        tap_action:
          action: perform-action
          perform_action: notify.mobile_app_oneplus_a3003
          data:
            message: command_volume_level
            data:
              media_stream: music_stream
              command: "{{value}}"
        step: 1
        autofill_entity_id: false
type: tile
entity: sensor.oneplus_a3003_volume_level_music
icon: mdi:music
name: Volumen
grid_options:
  columns: 12
  rows: 2
vertical: false
hide_state: false
tap_action:
  action: none
icon_tap_action:
  action: none
hold_action:
  action: more-info
```

I am trying to add a second actions to `tap_action` that requests a [sensor update](https://companion.home-assistant.io/docs/notifications/notification-commands/#update-sensors) but every time I put something there I break the hole yml.

Is this possible? if so, how?

Thanks!

**Comment by Nerwyn** [comment, marked as answer]
Technically you can't send more than one action. There are two ways around this:

1. Use a script with the `script.turn_on` action, passing the slider value as a variable.

```yaml
action: perform-action
perform_action: script.turn_on
target:
  entity_id: script.notify_and_update_volume
data:
  variables:
    volume: '{{ value }}'
```

2. Use the `eval` action to make multiple service calls with JavaScript.

```javascript
this.hass.callService('notify', 'oneplus_a3003_volume_level_music', { 
  message: 'command_volume_level',
  data: {
    media_stream: 'music_stream',
    command: '{{ value }}'
  }
});
this.hass.callService('notify', 'oneplus_a3003_volume_level_music', { 
  message: 'command_update_sensors',
});
```

If the issue is that the refresh takes too long and the slider is bouncing back to the old value, increase the update after action delay (`value_from_hass_delay` in yaml) to prevent the slider from retrieving a stale not-yet updated by the integration value from the backend.
