### DISCUSSION TITLE
I was not able to change an icon in a button

### DISCUSSION THREAD

**Discussion by BBE-FR** [Nerwyn/custom-card-features#96] [Q&A] [answered]
Hello.

I am using this wonderful feature generator to create a room card: 
![image](https://github.com/user-attachments/assets/e906c2b7-7245-4833-b5f7-1805a134b9b3)

But I would like the shutter button icon to match the state of the cover entity linked.

I managed thanks to the style to have the color changing, but I would like either:
- to be able to use the default entity icon
- to have the icon also changing from mdi:shutter to mdi:shutter-open depending the cover entity state defined into a template.

How and where can I do that ?

My code for information:
```
features:
  - type: custom:service-call
    entries:
      - type: button
        entity_id: plant.alocatia
        icon: mdi:flower
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("plant.alocatia", "alert") %}
                --icon-color: orange;
                {% endif %}
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Plante Marsupilami
              content:
                type: custom:flower-card
                entity: plant.alocatia
                show_bars:
                  - moisture
                  - temperature
                  - illuminance
                  - conductivity
                battery_sensor: sensor.alocasia_zebrina_battery
                display_type: compact
      - type: button
        entity_id: device_tracker.echo_jeanne
        icon: mdi:play-pause
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("media_player.echo_jeanne", "playing") %}
                --icon-color: blue;
                {% endif %}
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Echo salon
              content:
                type: custom:streamline-card
                template: pop-up-alexa
                variables:
                  media_player_entity_name: echo_jeanne
      - type: button
        entity_id: cover.volet_du_salon_apero
        icon: mdi:window-shutter
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("cover.salon", "open") %}
                --icon-color: orange;
                {% endif %}
          }
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Volets du salon
              content:
                type: vertical-stack
                cards:
                  - type: custom:mushroom-cover-card
                    entity: cover.volet_du_salon_apero
                    name: Volet Apero
                    show_position_control: true
                    show_tilt_position_control: false
                    show_buttons_control: true
                  - type: custom:mushroom-cover-card
                    entity: cover.volet_du_salon_tv
                    name: Volet TV
                    show_position_control: true
                    show_tilt_position_control: false
                    show_buttons_control: true
      - type: button
        entity_id: group.lumieres_salon
        hold_action:
          action: toggle
          target:
            entity_id: group.lumieres_salon
          data: {}
        haptics: true
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Lumières salon
              content:
                type: custom:streamline-card
                template: pop-up-light-salon
                variables: {}
        icon: mdi:lightbulb
        color: accent
        autofill_entity_id: true
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("light.0x84ba20fffe4b2581", "on") %}
                --icon-color: orange;
                {% endif %}
          }
    styles: ""
type: tile
features_position: bottom
vertical: false
entity: sensor.tuile_salon
color: accent
icon: ""
state_content:
  - Alexa
  - Marsu
grid_options:
  columns: 6
  rows: 2
icon_hold_action:
  action: perform-action
  perform_action: light.toggle
  target:
    entity_id: light.0x84ba20fffe4b2581
icon_tap_action:
  action: perform-action
  perform_action: ""

```

Thank you very much for help !
