### ISSUE TITLE
Card features work on Mac but throw an error on iPad and iPhone

### ISSUE THREAD

**Issue by The-Linux-User** [Nerwyn/custom-card-features#105]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser
- [ x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action) (I tried checking but I think the actions dev tool does is not suited for this case)

**Release with the issue:** 4.3.6

**Last working release (if known):** unknown

**Browser and Operating System:** iOS/iPadOS Safari and HA App

**Description of problem:**

The card is working fine on my MacBook using Safari but throws an error on both my iPad and iPhone in Safari and the Home Assistant App. On both devices I do not see the option to create custom card features when creating a new tile card from those devices. I found a similar issue (#3 ) but I was not able to solve this issue with the information given there.

**Javascript errors shown in the web inspector (if applicable):**

```
type: custom:service-call
entries:
  - type: toggle
    entity_id: input_boolean.automation_katzensicherung
    tap_action:
      action: toggle
      target:
        entity_id: input_boolean.automation_katzensicherung
      data: {}
    haptics: true
    thumb: md3-switch
    icon: ''
    unchecked_icon: ''
    label: |+


```

**Your Full Card Config**

```
features:
  - type: custom:service-call
    entries:
      - type: toggle
        entity_id: input_boolean.automation_katzensicherung
        tap_action:
          action: toggle
          target:
            entity_id: input_boolean.automation_katzensicherung
          data: {}
        haptics: true
        thumb: md3-switch
        icon: " "
        unchecked_icon: mdi:shield-off-outline
        label: " "
type: tile
features_position: bottom
vertical: false
icon: ""
color: light-blue
hide_state: true
entity: input_boolean.automation_katzensicherung
name: " Alarm Katzen Türen"

```

**Additional information:**
Things I tried:
- Cleared HA App Frontend Cache
- Restarted my Phone
- Reinstalled custom-card-features
- I tried creating a few different cards using different entities (using buttons, sliders, toggles) to check if it is an issue with this specific card

![Image](https://github.com/user-attachments/assets/8231d7fb-c929-4b23-acbf-ff83a82e5882)
