### ISSUE TITLE
Problems between tags 4.3.8 and 4.3.9

### ISSUE THREAD

**Issue by Revilo91** [Nerwyn/custom-card-features#113]
**Checklist:**

- [ ] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
Tag - 4.3.9

**Last working release (if known):**
Tag - 4.3.8

**Browser and Operating System:**
Google Chrome 135.0.7049.115 / Windows 11

**Description of problem:**
As soon as I update to the above version, the custom:service-call is no longer recognized, and I get this error message saying Hassio can't find it.

Has anything changed in the background?

All other tags before that were also checked, but only randomly.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Card Config**

```yaml
features:
  - type: cover-open-close
  - type: custom:service-call
    entries:
      - type: button
        entity_id: input_button.garagentor_luften
        label: Lüften
        icon: ""
        tap_action:
          action: toggle
          target:
            entity_id: input_button.garagentor_luften
          data: {}
          confirmation:
            text: Wirklich lüften?
        styles: |-
          :host {
            --color: lightgreen;
          }
      - type: button
        entity_id: automation.garagentor_xxx_auf
        label: xxx
        icon: ""
        tap_action:
          action: perform-action
          perform_action: automation.trigger
          target:
            entity_id:
              - automation.garagentor_xxx_auf
          data: {}
          confirmation:
            text: Wirklich öffnen?
        styles: |-
          :host {
            --color: orangered;
          }
        value_attribute: id
type: tile
entity: cover.eg_garagentor
state_content:
  - current_position
  - state
  - last-changed
features_position: bottom
vertical: true
icon_tap_action:
  action: none
grid_options:
  columns: full

```

**Additional information:**
