### ISSUE TITLE
Invisible slider

### ISSUE THREAD

**Issue by Ergoprett** [Nerwyn/custom-card-features#117]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.4.0

**Last working release (if known):**
4.3.11

**Browser and Operating System:**
Chrome & Windows
but also on android & iOS

**Description of problem:**

The slider changed in the newest update and is now displayed the wrong way. You can still use it, but you can't see the current state of the slider.

![Image](https://github.com/user-attachments/assets/59773cb8-a491-45f7-bdeb-313f5b65baab)

**Your Full Card Config**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: light.lampe
        range:
          - 1
          - 100
        tap_action:
          action: perform-action
          target:
            entity_id:
              - light.lampe
          perform_action: light.turn_on
          data:
            brightness_pct: "{{ value | float }}"
        step: 1
        value_attribute: brightness
        unit_of_measurement: "%"
        styles: ""
    styles: ""
type: tile
entity: light.lampe
grid_options:
  columns: 12
  rows: 1
hide_state: false
tap_action:
  action: none
icon_tap_action:
  action: more-info
features_position: bottom
vertical: false

```
