### ISSUE TITLE
stateObj not passed to selector options

### ISSUE THREAD

**Issue by BernardoEstrada** [Nerwyn/custom-card-features#121]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
Latest

**Last working release (if known):**
n/a

**Browser and Operating System:**
Chrome MacOS

**Description of problem:**

Selector button options don't get passed down stateObj 

**Your Full Card Config**

```yaml
type: tile
entity: climate.aire_estudio
features_position: bottom
vertical: false
hide_state: false
show_entity_picture: false
icon: m3rf:climate-mini-split
grid_options:
  columns: 12
  rows: auto
state_content: state
tap_action:
  action: toggle
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: "{{ stateObj.entity_id }}"
        value_attribute: >
          {% if is_state_attr('climate.aire_estudio', 'preset_mode', 'windFree')
          %} preset_mode {% else %} swing_mode {% endif %}
        haptics: true
        header: asd
        options:
          - entity_id: "{{ stateObj.entity_id }}" # <- this doesn't render
            option: "off"
            tap_action:
              action: perform-action
              perform_action: climate.set_swing_mode
              target:
                entity_id:
                  - "{{config.entity}}" # <- because config.entity_id is the plain text template, this fails
              data:
                swing_mode: "off"
            icon: mdi:arrow-oscillating-off
            value_attribute: swing_mode
            type: button
        value_from_hass_delay: 500
        styles: |-
          :host {
            .selected {
              --icon-color: var(--white-color);
            }
          }
```

**Additional information:**

Solution should be just to add
`.stateObj=${this.stateObj}`
to 
https://github.com/Nerwyn/custom-card-features/blob/730172499603e7087f914c7c91a7c920b04389e4/src/classes/custom-feature-selector.ts#L27-L33
